### ISSUE TITLE
Let the Renaming Fiasco Begin - QRAVEPlugin is now Riverscape Viewer (Q Plugin)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRAVEPlugin#92]
@philipbaileynar please add to this list and or tweak suggestions, but lets get on same page in the request here then you can task it out. We have decided that 
- all the RAVE products are being renamed to **Riverscapes Viewer**
- For short we refer to it as the **Viewer**
- Only where necessary if we need an abbreviation, we refer to the viewer as **RV**
- We de-emphasize the flavor of the viewer (e.g. Web, Q or Arc) in names, and demote these from prefixes that are part of the name to optional suffixes (added only for specificity) - e.g. this is the **Riverscape Viewer - Q Plugin** or **RV-Q**. 

## Tasks
- [ ] Update `Help` → `About QRAVE` to `About Riverscapes Viewer`
- [ ] Change About Dialog title from "**Riverscapes Analysis and Viewer Explorer**" to "**Riverscapes Viewer (QGIS Plugin)**"

This is hilarious that we don't even call this same thing it is on website! "Riverscapes Analysis Visualization Explorer"

- [x] Edit the [Acknowledgements Dialog](https://github.com/Riverscapes/RaveAddIn/blob/master/docs/dotnetack.md) in https://github.com/Riverscapes/RaveAddIn/pull/187
- [x] Update CNAME from rave to viewer such that new URL is https://viewer.riverscapes.net
- [x] Plumb redirect from https://rave.riverscapes.net to https://viewer.riverscapes.net
- [x] Change title of main dockable panel from "Riverscapes Toolbar (QRAVE)" to "Riverscapes Viewer"
- [x] Change the `View in Warehouse` right-click command for riverscape projects to `View in Riverscapes Data Exchange`
- [x] Change Icon for first button from old RC Logo to new RC Viewer Logo
- [x] Change tooltip for RC button from "Riverscapes Plugin (QRAVE)" to "Open/Close Riverscapes Viewer Panel"
- [x] Consider changing Repo Name from QRAVE to Viewer_
- [x] Change registration in Plugin Library from "Riverscapes Plugin (QRAVE)" to "Riverscapes Viewer"
- [x] Change description 
![image](https://user-images.githubusercontent.com/9723905/230913740-34e37a7a-de5a-4322-9ecd-16fcd5118ba4.png)
to
>**Explore symbolized Riverscapes projects**
>
> The **Riverscapes Viewer** is an Application from the Riverscapes Consortium (https://riverscapes.net). The viewer allows visualization of any "Riverscapes Project" including those available for download in the Riverscapes Data Exchange (https://data.riverscapes.net). These projects can contain a mix of GIS and non-geospatial data, and the Viewer allows you view the project contents in its “project tree”, and add any layer to map symbolized appropriately. This QGIS Plugin version of Riverscapes Viewer is one the desktop GIS viewers (also an AddIn for ArcGIS 10.x and ArcPro on the way). There is also a web-version of the Riverscapes Viewer available when accessing any project in the Riverscapes Data Exchange. The Riverscapes Viewer also is a requirement for the sister tool, the **Riverscapes Studio** (also available as a QGIS plugin).

- [ ] Make similar ticket and tasks for Riverscapes Viewer - ArcGIS (https://github.com/Riverscapes/RaveAddIn/)
- [x] Make similar ticket for Riverscapes Viewer - Web

**Comment by philipbaileynar** [comment]
What's the URL subdomain instead of rave.riverscapes.net?

viewer.riverscapes.net?

**Comment by joewheaton** [comment]
@philipbaileynar and @KellyMWhitehead I think you did all of this except the ArcViewer shit. I'm not sure if we should do that. I am closing this old issue. Reopen if you disagree.
